### NumPy
Lavora con array, vettori e matrici.

Se necessario la installiamo con pip install numpy. 


In [107]:
import numpy as np

Creo un primo array.

In [108]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Creo una matrice

In [109]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Per esaminare la struttura dei dati di numpy e capire se è una matrice, una lsta  un array usiamo shape:

In [110]:
v1.shape

(9,)

In [111]:
m1.shape

(3, 3)

La proprietà shape si può usare per modificare la forma dei dati. Es. da una lista passo a una matrice. 

L'importante è che righe x colonne = numero elementi

In [112]:
v2 = np.array([1,2,3,4,5,6,7,8,9])
print("prima forma:", v2.shape)
v2.shape=(3,3)
print("dopo la trasformazione:", v2.shape)

prima forma: (9,)
dopo la trasformazione: (3, 3)


Tutti gli elementi di una __lista np__ sono __sempre omogenei__ diversamente dalle liste in Python.

_dtype_ riporta il tipo di dati della lista.

In [113]:
v2.dtype

dtype('int64')

Provo a inserire un numero con virgola nell'array _v2_. Purtroppo il tipo è definito e non è possibile modificarlo. L'elemento inserito perde la virgola.

Vediamo anche come inserire un elemento in una posizione: basta usare le [] con gli indici.

In [114]:
#non va?
v2[1,1] = 3.3
print(v2)
v2.dtype

[[1 2 3]
 [4 3 6]
 [7 8 9]]


dtype('int64')

Per modificare il tipo di dati creo un nuovo array passandogli l'array da copiare (v2) e il nuovo tip di dati.

In [115]:
y= np.array(v2, dtype=float)
y[1,1] = 3.5
print(y)
y.dtype

[[1.  2.  3. ]
 [4.  3.5 6. ]
 [7.  8.  9. ]]


dtype('float64')

_dtype_ si può usare per forzare il tipo di dato dell'array una volta che è stato definito.

In [118]:
a1 = np.array([1,2,3,4,5])
print("il tipo prima: ", a1.dtype)
a1.dtype = np.float64
print("il tipo dopo la modifica: ", a1.dtype)
print(a1)

il tipo prima:  int64
il tipo dopo la modifica:  float64
[4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


## tipi dato ##
numpy gestisce tanti tipi di dato: int8/16/32, uint8/16/32/64, intp (per indexing) uintp (per puntatori), float32/64, complex64/128

In [120]:
c1 = np.array([1+1j, 2+3j, 3-2j])
print(c1)
print("somma di complessi: ", (c1[0] + c1[1]))

[1.+1.j 2.+3.j 3.-2.j]
somma di complessi:  (3+4j)


## operazioni ##


In [130]:
a = np.array([25, 50, 75, 100])
b = np.array([12, 23, 34, 45])

print("a+b", a+b)
print("a-b", a-b)
print("a*b", a*b)
print("a * 0.5 (modifica tipo): ", (a*0.5))
print("confronto a > 60", (a>60))

a+b [ 37  73 109 145]
a-b [13 27 41 55]
a*b [ 300 1150 2550 4500]
a * 0.5 (modifica tipo):  [12.5 25.  37.5 50. ]
confronto a > 60 [False False  True  True]


## generare array ##
